name: Build Minecraft Mod

on:
  push:
    branches:
      - master  # Trigger the build on push to the master branch
  pull_request:
    branches:
      - master  # Trigger the build on pull requests to the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Give Gradle wrapper execute permission
        run: chmod +x gradlew
      - name: Build the mod
        run: ./gradlew build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
